[profile.release-with-debug]
inherits = "release"
debug = true
split-debuginfo = "packed"

[patch.crates-io]
# for details, see https://github.com/anza-xyz/crossbeam/commit/fd279d707025f0e60951e429bf778b4813d1b6bf
crossbeam-epoch = { git = "https://github.com/anza-xyz/crossbeam", rev = "fd279d707025f0e60951e429bf778b4813d1b6bf" }

# We include the following crates as our dependencies above from crates.io:
#
#  * spl-associated-token-account
#  * spl-instruction-padding
#  * spl-memo
#  * spl-pod
#  * spl-token
#  * spl-token-2022
#  * spl-token-metadata-interface
#
# They, in turn, depend on a number of crates that we also include directly
# using `path` specifications.  For example, `spl-token` depends on
# `solana-program`.  And we explicitly specify `solana-program` above as a local
# path dependency:
#
#     solana-program = { path = "../../sdk/program", version = "=1.16.0" }
#
# Unfortunately, Cargo will try to resolve the `spl-token` `solana-program`
# dependency only using what is available on crates.io.  Crates.io normally
# contains a previous version of these crates, and we end up with two versions
# of `solana-program` and `solana-zk-token-sdk` and all of their dependencies in
# our build tree.
#
# If you are developing downstream using non-crates-io solana-program (local or
# forked repo, or from github rev, eg), duplicate the following patch statements
# in your Cargo.toml. If you still hit duplicate-type errors with the patch
# statements in place, run `cargo update -p solana-program` and/or `cargo update
# -p solana-zk-token-sdk` to remove extraneous versions from your Cargo.lock
# file.
#
# There is a similar override in `programs/sbf/Cargo.toml`.  Please keep both
# comments and the overrides in sync.
solana-curve25519 = {path = "../fd_agave/curves/curve25519"}
solana-program = {path = "../fd_agave/sdk/program"}
solana-zk-sdk = {path = "../fd_agave/zk-sdk"}
solana-zk-token-sdk = {path = "../fd_agave/zk-token-sdk"}

# curve25519-dalek uses the simd backend by default in v4 if possible,
# which has very slow performance on some platforms with opt-level 0,
# which is the default for dev and test builds.
# This slowdown causes certain interactions in the solana-test-validator,
# such as verifying ZK proofs in transactions, to take much more than 400ms,
# creating problems in the testing environment.
# To enable better performance in solana-test-validator during tests and dev builds,
# we override the opt-level to 3 for the crate.
[profile.dev.package.curve25519-dalek]
opt-level = 3

# Solana RPC nodes experience stalls when running with `tokio` containing this
# commit:
# https://github.com/tokio-rs/tokio/commit/4eed411519783ef6f58cbf74f886f91142b5cfa6
#
# Tokio maintainers believe performance degradation is due to application bugs:
# https://github.com/tokio-rs/tokio/issues/4873#issuecomment-1198277677
#
# This may indeed be true of the code in this monorepo, but we haven't yet
# identified the bug or a way to fix. As a stopgap, this patches `tokio` to the
# tagged version specified above with commit `4eed411` reverted.
#
# Comparison:
# https://github.com/tokio-rs/tokio/compare/tokio-1.29.1...solana-labs:solana-tokio:tokio-1.29.1-revert-4eed411
#
[patch.crates-io.tokio]
git = "https://github.com/anza-xyz/solana-tokio.git"
rev = "7cf47705faacf7bf0e43e4131a5377b3291fce21"

[package]
name = "solfuzz-agave"
version = "0.1.0"
edition = "2021"

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
    'cfg(target_os, values("solana"))',
    'cfg(feature, values("frozen-abi", "no-entrypoint"))',
]


[dependencies]
Inflector = "0.11.4"
agave-transaction-view = {path = "../fd_agave/transaction-view"}
aquamarine = "0.3.3"
aes-gcm-siv = "0.11.1"
ahash = "0.8.11"
anyhow = "1.0.91"
arbitrary = "1.3.2"
ark-bn254 = "0.4.0"
ark-ec = "0.4.0"
ark-ff = "0.4.0"
ark-serialize = "0.4.0"
array-bytes = "=1.4.1"
arrayref = "0.3.9"
arrayvec = "0.7.6"
assert_cmd = "2.0"
assert_matches = "1.5.0"
async-channel = "1.9.0"
async-lock = "3.4.0"
async-trait = "0.1.83"
atty = "0.2.11"
backoff = "0.4.0"
base64 = "0.22.1"
bincode = "1.3.3"
bitflags = { version = "2.6.0" }
blake3 = "1.5.4"
borsh = { version = "1.5.1", features = ["derive", "unstable__schema"] }
borsh0-10 = { package = "borsh", version = "0.10.3" }
bs58 = { version = "0.5.1", default-features = false }
bv = "0.11.1"
byte-unit = "4.0.19"
bytecount = "0.6.8"
bytemuck = "1.19.0"
bytemuck_derive = "1.8.0"
byteorder = "1.5.0"
bytes = "1.8"
bzip2 = "0.4.4"
caps = "0.5.5"
cargo_metadata = "0.15.4"
cfg_eval = "0.1.2"
chrono = { version = "0.4.38", default-features = false }
chrono-humanize = "0.2.3"
clap = { version = "4.5.2", features = ["derive"] }
console = "0.15.8"
console_error_panic_hook = "0.1.7"
console_log = "0.2.2"
const_format = "0.2.33"
core_affinity = "0.5.10"
criterion = "0.5.1"
criterion-stats = "0.3.0"
crossbeam-channel = "0.5.13"
csv = "1.3.0"
ctrlc = "3.4.5"
curve25519-dalek = { version = "4.1.3", features = ["digest", "rand_core"] }
dashmap = "5.5.3"
derivation-path = { version = "0.2.0", default-features = false }
derivative = "2.2.0"
dialoguer = "0.10.4"
digest = "0.10.7"
dir-diff = "0.3.3"
dirs-next = "2.0.0"
dlopen2 = "0.5.0"
eager = "0.1.0"
ed25519-dalek = "=1.0.1"
ed25519-dalek-bip32 = "0.2.0"
enum-iterator = "1.5.0"
env_logger = "0.9.3"
etcd-client = "0.11.1"
fast-math = "0.1"
fd-lock = "3.0.13"
flate2 = "1.0.31"
five8_const = "0.1.3"
fnv = "1.0.7"
fs_extra = "1.3.0"
futures = "0.3.31"
futures-util = "0.3.29"
gag = "1.0.0"
generic-array = { version = "0.14.7", default-features = false }
gethostname = "0.2.3"
getrandom = "0.2.10"
goauth = "0.13.1"
governor = "0.6.3"
hex = "0.4.3"
hidapi = { version = "2.6.3", default-features = false }
histogram = "0.6.9"
hmac = "0.12.1"
http = "0.2.12"
humantime = "2.0.1"
hyper = "0.14.31"
hyper-proxy = "0.9.1"
im = "15.1.0"
index_list = "0.2.13"
indexmap = "2.6.0"
indicatif = "0.17.8"
itertools = "0.12.1"
jemallocator = { package = "tikv-jemallocator", version = "0.4.1", features = [
    "unprefixed_malloc_on_supported_platforms",
] }
js-sys = "0.3.72"
json5 = "0.4.1"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive = "18.0.0"
jsonrpc-http-server = "18.0.0"
jsonrpc-ipc-server = "18.0.0"
jsonrpc-pubsub = "18.0.0"
lazy-lru = "0.1.3"
lazy_static = "1.5.0"
libc = "0.2.161"
libloading = "0.7.4"
libsecp256k1 = { version = "0.6.0", default-features = false, features = [
    "std",
    "static-context",
] }
light-poseidon = "0.2.0"
log = "0.4.22"
lru = "0.7.7"
lz4 = "1.28.0"
memmap2 = "0.5.10"
memoffset = "0.9"
merlin = "3"
min-max-heap = "1.3.0"
mockall = "0.11.4"
modular-bitfield = "0.11.2"
nix = "0.29.0"
num-bigint = "0.4.6"
num-derive = "0.4"
num-traits = "0.2"
num_cpus = "1.16.0"
num_enum = "0.7.3"
openssl = "0.10"
parking_lot = "0.12"
pbkdf2 = { version = "0.11.0", default-features = false }
pem = "1.1.1"
percentage = "0.1.0"
predicates = "2.1"
pretty-hex = "0.3.0"
prio-graph = "0.3.0"
proc-macro2 = "1.0.89"
proptest = "1.5"
prost = "0.11.9"
prost-build = "0.11.9"
prost-types = "0.11.9"
protobuf-src = "1.1.0"
qstring = "0.7.2"
qualifier_attr = { version = "0.2.2", default-features = false }
quinn = "0.11.6"
quinn-proto = "0.11.9"
quote = "1.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
rayon = "1.10.0"
reed-solomon-erasure = "6.0.0"
regex = "1.11.1"
reqwest = { version = "0.11.27", default-features = false }
reqwest-middleware = "0.2.5"
rolling-file = "0.2.0"
rpassword = "7.3"
rustls = { version = "0.23.15", default-features = false }
scopeguard = "1.2.0"
semver = "1.0.23"
seqlock = "0.2.0"
serde = "1.0.213" # must match the serde_derive version, see https://github.com/serde-rs/serde/issues/2584#issuecomment-1685252251
serde_bytes = "0.11.15"
serde_derive = "1.0.213" # must match the serde version, see https://github.com/serde-rs/serde/issues/2584#issuecomment-1685252251
serde_json = "1.0.132"
serde_with = { version = "3.11.0", default-features = false }
serde_yaml = "0.9.34"
serial_test = "2.0.0"
sha2 = "0.10.8"
sha3 = "0.10.8"
shuttle = "0.7.1"
signal-hook = "0.3.17"
siphasher = "0.3.11"
smallvec = "1.13.2"
smpl_jwt = "0.7.1"
socket2 = "0.5.7"
soketto = "0.7"
solana-account = {path = "../fd_agave/sdk/account"}
solana-account-decoder = {path = "../fd_agave/account-decoder"}
solana-account-decoder-client-types = {path = "../fd_agave/account-decoder-client-types"}
solana-account-info = {path = "../fd_agave/sdk/account-info"}
solana-accounts-db = {path = "../fd_agave/accounts-db"}
solana-address-lookup-table-program = {path = "../fd_agave/programs/address-lookup-table"}
solana-atomic-u64 = {path = "../fd_agave/sdk/atomic-u64"}
solana-banks-client = {path = "../fd_agave/banks-client"}
solana-banks-interface = {path = "../fd_agave/banks-interface"}
solana-banks-server = {path = "../fd_agave/banks-server"}
solana-bench-tps = {path = "../fd_agave/bench-tps"}
solana-bincode = {path = "../fd_agave/sdk/bincode"}
solana-bloom = {path = "../fd_agave/bloom"}
solana-bn254 = {path = "../fd_agave/curves/bn254"}
solana-borsh = {path = "../fd_agave/sdk/borsh"}
solana-bpf-loader-program = {path = "../fd_agave/programs/bpf_loader"}
solana-bucket-map = {path = "../fd_agave/bucket_map"}
solana-builtins-default-costs = {path = "../fd_agave/builtins-default-costs"}
agave-cargo-registry = {path = "../fd_agave/cargo-registry"}
solana-clap-utils = {path = "../fd_agave/clap-utils"}
solana-clap-v3-utils = {path = "../fd_agave/clap-v3-utils"}
solana-cli = {path = "../fd_agave/cli"}
solana-cli-config = {path = "../fd_agave/cli-config"}
solana-cli-output = {path = "../fd_agave/cli-output"}
solana-client = {path = "../fd_agave/client"}
solana-clock = {path = "../fd_agave/sdk/clock"}
solana-compute-budget = {path = "../fd_agave/compute-budget"}
solana-compute-budget-program = {path = "../fd_agave/programs/compute-budget"}
solana-config-program = {path = "../fd_agave/programs/config"}
solana-connection-cache = {path = "../fd_agave/connection-cache"}
solana-core = {path = "../fd_agave/core"}
solana-cost-model = {path = "../fd_agave/cost-model"}
solana-cpi = {path = "../fd_agave/sdk/cpi"}
solana-curve25519 = {path = "../fd_agave/curves/curve25519"}
solana-decode-error = {path = "../fd_agave/sdk/decode-error"}
solana-define-syscall = {path = "../fd_agave/define-syscall"}
solana-derivation-path = {path = "../fd_agave/sdk/derivation-path"}
solana-download-utils = {path = "../fd_agave/download-utils"}
solana-entry = {path = "../fd_agave/entry"}
solana-program-entrypoint = {path = "../fd_agave/sdk/program-entrypoint"}
solana-epoch-schedule = {path = "../fd_agave/sdk/epoch-schedule"}
solana-faucet = {path = "../fd_agave/faucet"}
solana-feature-set = {path = "../fd_agave/sdk/feature-set"}
solana-fee-calculator = {path = "../fd_agave/sdk/fee-calculator"}
solana-fee = {path = "../fd_agave/fee"}
solana-frozen-abi = {path = "../fd_agave/frozen-abi"}
solana-frozen-abi-macro = {path = "../fd_agave/frozen-abi/macro"}
solana-tps-client = {path = "../fd_agave/tps-client"}
solana-genesis = {path = "../fd_agave/genesis"}
solana-genesis-utils = {path = "../fd_agave/genesis-utils"}
agave-geyser-plugin-interface = {path = "../fd_agave/geyser-plugin-interface"}
solana-geyser-plugin-manager = {path = "../fd_agave/geyser-plugin-manager"}
solana-gossip = {path = "../fd_agave/gossip"}
solana-hash = {path = "../fd_agave/sdk/hash"}
solana-inflation = {path = "../fd_agave/sdk/inflation"}
solana-inline-spl = {path = "../fd_agave/inline-spl"}
solana-instruction = {path = "../fd_agave/sdk/instruction"}
solana-last-restart-slot = {path = "../fd_agave/sdk/last-restart-slot"}
solana-lattice-hash = {path = "../fd_agave/lattice-hash"}
solana-ledger = {path = "../fd_agave/ledger"}
solana-loader-v4-program = {path = "../fd_agave/programs/loader-v4"}
solana-local-cluster = {path = "../fd_agave/local-cluster"}
solana-log-collector = {path = "../fd_agave/log-collector"}
solana-logger = {path = "../fd_agave/logger"}
solana-measure = {path = "../fd_agave/measure"}
solana-merkle-tree = {path = "../fd_agave/merkle-tree"}
solana-metrics = {path = "../fd_agave/metrics"}
solana-msg = {path = "../fd_agave/sdk/msg"}
solana-native-token = {path = "../fd_agave/sdk/native-token"}
solana-net-utils = {path = "../fd_agave/net-utils"}
solana-nohash-hasher = "0.2.1"
solana-notifier = {path = "../fd_agave/notifier"}
solana-package-metadata = {path = "../fd_agave/sdk/package-metadata"}
solana-package-metadata-macro = {path = "../fd_agave/sdk/package-metadata-macro"}
solana-packet = {path = "../fd_agave/sdk/packet"}
solana-perf = {path = "../fd_agave/perf"}
solana-poh = {path = "../fd_agave/poh"}
solana-poseidon = {path = "../fd_agave/poseidon"}
solana-precompile-error = {path = "../fd_agave/sdk/precompile-error"}
solana-program = {path = "../fd_agave/sdk/program"}
solana-program-error = {path = "../fd_agave/sdk/program-error"}
solana-program-memory = {path = "../fd_agave/sdk/program-memory"}
solana-program-option = {path = "../fd_agave/sdk/program-option"}
solana-program-pack = {path = "../fd_agave/sdk/program-pack"}
solana-program-runtime = {path = "../fd_agave/program-runtime"}
solana-program-test = {path = "../fd_agave/program-test"}
solana-pubkey = {path = "../fd_agave/sdk/pubkey"}
solana-pubsub-client = {path = "../fd_agave/pubsub-client"}
solana-quic-client = {path = "../fd_agave/quic-client"}
solana-rayon-threadlimit = {path = "../fd_agave/rayon-threadlimit"}
solana-remote-wallet = {path = "../fd_agave/remote-wallet"}
solana-rent = {path = "../fd_agave/sdk/rent"}
solana-sanitize = {path = "../fd_agave/sdk/sanitize"}
solana-secp256r1-program = {path = "../fd_agave/sdk/secp256r1-program"}
solana-serde-varint = {path = "../fd_agave/sdk/serde-varint"}
solana-serialize-utils = {path = "../fd_agave/sdk/serialize-utils"}
solana-sha256-hasher = {path = "../fd_agave/sdk/sha256-hasher"}
solana-signature = {path = "../fd_agave/sdk/signature"}
solana-slot-hashes = {path = "../fd_agave/sdk/slot-hashes"}
solana-slot-history = {path = "../fd_agave/sdk/slot-history"}
solana-timings = {path = "../fd_agave/timings"}
solana-unified-scheduler-logic = {path = "../fd_agave/unified-scheduler-logic"}
solana-unified-scheduler-pool = {path = "../fd_agave/unified-scheduler-pool"}
solana-rpc = {path = "../fd_agave/rpc"}
solana-rpc-client = {path = "../fd_agave/rpc-client"}
solana-rpc-client-api = {path = "../fd_agave/rpc-client-api"}
solana-rpc-client-nonce-utils = {path = "../fd_agave/rpc-client-nonce-utils"}
solana-runtime = {path = "../fd_agave/runtime"}
solana-runtime-transaction = {path = "../fd_agave/runtime-transaction"}
solana-sdk = {path = "../fd_agave/sdk"}
solana-sdk-macro = {path = "../fd_agave/sdk/macro"}
solana-secp256k1-recover = {path = "../fd_agave/curves/secp256k1-recover"}
solana-send-transaction-service = {path = "../fd_agave/send-transaction-service"}
solana-short-vec = {path = "../fd_agave/short-vec"}
solana-stable-layout = {path = "../fd_agave/sdk/stable-layout"}
solana-stake-program = {path = "../fd_agave/programs/stake"}
solana-storage-bigtable = {path = "../fd_agave/storage-bigtable"}
solana-storage-proto = {path = "../fd_agave/storage-proto"}
solana-streamer = {path = "../fd_agave/streamer"}
solana-svm = {path = "../fd_agave/svm"}
solana-svm-conformance = {path = "../fd_agave/svm-conformance"}
solana-svm-example-paytube = {path = "../fd_agave/svm/examples/paytube"}
solana-svm-rent-collector = {path = "../fd_agave/svm-rent-collector"}
solana-svm-transaction = {path = "../fd_agave/svm-transaction"}
solana-system-program = {path = "../fd_agave/programs/system"}
solana-sysvar-id = {path = "../fd_agave/sdk/sysvar-id"}
solana-test-validator = {path = "../fd_agave/test-validator"}
solana-thin-client = {path = "../fd_agave/thin-client"}
solana-transaction-error = {path = "../fd_agave/sdk/transaction-error"}
solana-tpu-client = {path = "../fd_agave/tpu-client"}
solana-tpu-client-next = {path = "../fd_agave/tpu-client-next"}
solana-transaction-status = {path = "../fd_agave/transaction-status"}
solana-transaction-status-client-types = {path = "../fd_agave/transaction-status-client-types"}
solana-transaction-metrics-tracker = {path = "../fd_agave/transaction-metrics-tracker"}
solana-turbine = {path = "../fd_agave/turbine"}
solana-type-overrides = {path = "../fd_agave/type-overrides"}
solana-udp-client = {path = "../fd_agave/udp-client"}
solana-version = {path = "../fd_agave/version"}
solana-vote = {path = "../fd_agave/vote"}
solana-vote-program = {path = "../fd_agave/programs/vote"}
solana-wen-restart = {path = "../fd_agave/wen-restart"}
solana-zk-elgamal-proof-program = {path = "../fd_agave/programs/zk-elgamal-proof"}
solana-zk-keygen = {path = "../fd_agave/zk-keygen"}
solana-zk-sdk = {path = "../fd_agave/zk-sdk"}
solana-zk-token-proof-program = {path = "../fd_agave/programs/zk-token-proof"}
solana-zk-token-sdk = {path = "../fd_agave/zk-token-sdk"}
solana_rbpf = { git = "https://github.com/solana-labs/rbpf", rev = "410a627" }
spl-associated-token-account = "=4.0.0"
spl-instruction-padding = "0.2"
spl-memo = "=5.0.0"
spl-pod = "=0.3.0"
spl-token = "=6.0.0"
spl-token-2022 = "=4.0.0"
spl-token-group-interface = "=0.3.0"
spl-token-metadata-interface = "=0.4.0"
static_assertions = "1.1.0"
stream-cancel = "0.8.2"
strum = "0.24"
strum_macros = "0.24"
subtle = "2.6.1"
symlink = "0.1.0"
syn = "2.0"
sys-info = "0.9.1"
sysctl = "0.4.6"
systemstat = "0.2.3"
tar = "0.4.42"
tarpc = "0.29.0"
tempfile = "3.13.0"
test-case = "3.3.1"
thiserror = "1.0.65"
tiny-bip39 = "0.8.2"
# Update solana-tokio patch below when updating this version
tokio = "1.29.1"
tokio-serde = "0.8"
tokio-stream = "0.1.16"
tokio-tungstenite = "0.20.1"
tokio-util = "0.7"
toml = "0.8.12"
tonic = "0.9.2"
tonic-build = "0.9.2"
trees = "0.4.2"
tungstenite = "0.20.1"
uriparse = "0.6.4"
url = "2.5.2"
vec_extract_if_polyfill = "0.1.0"
wasm-bindgen = "0.2"
winapi = "0.3.8"
x509-parser = "0.14.0"
# See "zeroize versioning issues" below if you are updating this version.
zeroize = { version = "1.7", default-features = false }
zstd = "0.13.2"
solfuzz-agave-macro = { path = "macro" }

[lib]
crate-type = ["cdylib", "rlib"]

[build-dependencies]
prost-build = "0.13.1"

[features]
core-bpf = []
core-bpf-conformance = []
stub-agave = ["solana-program-runtime/stub-proc-instr"]
