#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

docker build --platform=linux/amd64 -t agave-v3.1.0-beta.0-patches .
docker run -it -v $DIR:/app -w /app agave-v3.1.0-beta.0-patches
