[package]
name = "solfuzz-agave"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "bench_txn"
harness = false

[dependencies]
clap = { version = "4.5.2", features = ["derive"] }
solfuzz-agave-macro = { path = "macro" }
once_cell = "1.21.3"
lazy_static = "1.5.0"
home = "0.5.11"
flatbuffers = "25.9.23"

[lib]
crate-type = ["cdylib", "rlib"]

[build-dependencies]
prost-build = "0.13.1"
flatc-rust = "0.2.0"

[features]
# This feature is used to compile a target with a builtin replaced by a BPF program.
# Requires the `CORE_BPF_PROGRAM_ID` and `CORE_BPF_TARGET` environment variables.
core-bpf = []
# Same as the `core-bpf` feature, but also includes special-casing required for
# conformance testing a BPF program against a builtin.
core-bpf-conformance = []
bpf-program-conformance = []
