// This file is auto-generated by scripts/generate_types_map.py
// Do not edit this file directly.
use crate::proto::TypeEffects;
use crate::types::types_processor::process_type;
use std::collections::HashMap;

// Type imports
use solana_accounts_db::blockhash_queue::HashInfo;
use solana_clock::Clock;
use solana_config_program::ConfigKeys;
use solana_core::repair::serve_repair::RepairProtocol;
use solana_core::repair::serve_repair::RepairRequestHeader;
use solana_epoch_rewards::EpochRewards;
use solana_feature_gate_interface::Feature;
use solana_fee_calculator::FeeCalculator;
use solana_fee_calculator::FeeRateGovernor;
use solana_gossip::crds_data::CrdsData;
use solana_gossip::crds_gossip_pull::CrdsFilter;
use solana_gossip::crds_value::CrdsValue;
use solana_hard_forks::HardForks;
use solana_hash::Hash;
use solana_inflation::Inflation;
use solana_last_restart_slot::LastRestartSlot;
use solana_ledger::blockstore_meta::DuplicateSlotProof;
use solana_ledger::blockstore_meta::FrozenHashStatus;
use solana_ledger::blockstore_meta::FrozenHashVersioned;
use solana_poh_config::PohConfig;
use solana_rent_collector::RentCollector;
use solana_runtime::bank::BankHashStats;
use solana_runtime::epoch_stakes::EpochStakes;
use solana_runtime::epoch_stakes::NodeVoteAccounts;
use solana_runtime::epoch_stakes::VersionedEpochStakes;
use solana_runtime::serde_snapshot::BankIncrementalSnapshotPersistence;
use solana_signature::Signature;
use solana_sysvar::epoch_schedule::EpochSchedule;
use solana_sysvar::rent::Rent;
use solana_sysvar::stake_history::StakeHistoryEntry;
use solana_vote::vote_account::VoteAccounts;
type TypeProcessorFn = fn(&[u8]) -> Option<TypeEffects>;

fn build_type_processor_map() -> HashMap<u8, TypeProcessorFn> {
    let mut map: HashMap<u8, TypeProcessorFn> = HashMap::new();

    map.insert(0, process_type::<Hash>);
    map.insert(2, process_type::<Signature>);
    map.insert(5, process_type::<Feature>);
    map.insert(6, process_type::<FeeCalculator>);
    map.insert(7, process_type::<HashInfo>);
    map.insert(11, process_type::<FeeRateGovernor>);
    map.insert(13, process_type::<HardForks>);
    map.insert(14, process_type::<Inflation>);
    map.insert(15, process_type::<Rent>);
    map.insert(16, process_type::<EpochSchedule>);
    map.insert(17, process_type::<RentCollector>);
    map.insert(18, process_type::<StakeHistoryEntry>);
    map.insert(27, process_type::<VoteAccounts>);
    map.insert(38, process_type::<BankIncrementalSnapshotPersistence>);
    map.insert(39, process_type::<NodeVoteAccounts>);
    map.insert(42, process_type::<EpochStakes>);
    map.insert(47, process_type::<BankHashStats>);
    map.insert(55, process_type::<VersionedEpochStakes>);
    map.insert(61, process_type::<PohConfig>);
    map.insert(65, process_type::<Clock>);
    map.insert(66, process_type::<LastRestartSlot>);
    map.insert(97, process_type::<EpochRewards>);
    map.insert(158, process_type::<ConfigKeys>);
    map.insert(174, process_type::<FrozenHashStatus>);
    map.insert(175, process_type::<FrozenHashVersioned>);
    map.insert(212, process_type::<CrdsData>);
    map.insert(214, process_type::<CrdsFilter>);
    map.insert(215, process_type::<CrdsValue>);
    map.insert(224, process_type::<RepairRequestHeader>);
    map.insert(229, process_type::<RepairProtocol>);
    map.insert(244, process_type::<DuplicateSlotProof>);

    map
}

use std::sync::LazyLock;
pub static TYPE_PROCESSORS: LazyLock<HashMap<u8, TypeProcessorFn>> =
    LazyLock::new(build_type_processor_map);
