// This file is auto-generated by scripts/generate_types_map.py
// Do not edit this file directly.
use crate::proto::TypeEffects;
use crate::types::types_processor::process_type;
use std::collections::HashMap;

// Type imports
use solana_accounts_db::blockhash_queue::HashInfo;
use solana_clock::Clock;
use solana_config_program::ConfigKeys;
use solana_core::repair::serve_repair::RepairProtocol;
use solana_core::repair::serve_repair::RepairRequestHeader;
use solana_epoch_rewards::EpochRewards;
use solana_fee_calculator::FeeCalculator;
use solana_fee_calculator::FeeRateGovernor;
use solana_gossip::crds_data::CrdsData;
use solana_gossip::crds_gossip_pull::CrdsFilter;
use solana_gossip::crds_value::CrdsValue;
use solana_hard_forks::HardForks;
use solana_hash::Hash;
use solana_inflation::Inflation;
use solana_last_restart_slot::LastRestartSlot;
use solana_ledger::blockstore_meta::DuplicateSlotProof;
use solana_ledger::blockstore_meta::FrozenHashStatus;
use solana_ledger::blockstore_meta::FrozenHashVersioned;
use solana_poh_config::PohConfig;
use solana_program::sysvar::epoch_schedule::EpochSchedule;
use solana_program::sysvar::rent::Rent;
use solana_program::sysvar::stake_history::StakeHistory;
use solana_program::sysvar::stake_history::StakeHistoryEntry;
use solana_rent_collector::RentCollector;
use solana_runtime::bank::BankHashStats;
use solana_runtime::epoch_stakes::EpochStakes;
use solana_runtime::epoch_stakes::NodeVoteAccounts;
use solana_runtime::epoch_stakes::VersionedEpochStakes;
use solana_runtime::serde_snapshot::BankIncrementalSnapshotPersistence;
use solana_sdk::feature::Feature;
use solana_sdk::signature::Signature;
use solana_vote::vote_account::VoteAccounts;
type TypeProcessorFn = fn(&[u8]) -> Option<TypeEffects>;

fn build_type_processor_map() -> HashMap<u8, TypeProcessorFn> {
    let mut map: HashMap<u8, TypeProcessorFn> = HashMap::new();

    map.insert(0, process_type::<Hash>);
    map.insert(2, process_type::<Signature>);
    map.insert(5, process_type::<Feature>);
    map.insert(6, process_type::<FeeCalculator>);
    map.insert(7, process_type::<HashInfo>);
    map.insert(11, process_type::<FeeRateGovernor>);
    map.insert(13, process_type::<HardForks>);
    map.insert(14, process_type::<Inflation>);
    map.insert(15, process_type::<Rent>);
    map.insert(16, process_type::<EpochSchedule>);
    map.insert(17, process_type::<RentCollector>);
    map.insert(18, process_type::<StakeHistoryEntry>);
    map.insert(20, process_type::<StakeHistory>);
    map.insert(23, process_type::<VoteAccounts>);
    map.insert(34, process_type::<BankIncrementalSnapshotPersistence>);
    map.insert(35, process_type::<NodeVoteAccounts>);
    map.insert(38, process_type::<EpochStakes>);
    map.insert(43, process_type::<BankHashStats>);
    map.insert(51, process_type::<VersionedEpochStakes>);
    map.insert(57, process_type::<PohConfig>);
    map.insert(61, process_type::<Clock>);
    map.insert(62, process_type::<LastRestartSlot>);
    map.insert(93, process_type::<EpochRewards>);
    map.insert(154, process_type::<ConfigKeys>);
    map.insert(170, process_type::<FrozenHashStatus>);
    map.insert(171, process_type::<FrozenHashVersioned>);
    map.insert(206, process_type::<CrdsData>);
    map.insert(208, process_type::<CrdsFilter>);
    map.insert(209, process_type::<CrdsValue>);
    map.insert(218, process_type::<RepairRequestHeader>);
    map.insert(223, process_type::<RepairProtocol>);
    map.insert(238, process_type::<DuplicateSlotProof>);

    map
}

use once_cell::sync::Lazy;
pub static TYPE_PROCESSORS: Lazy<HashMap<u8, TypeProcessorFn>> =
    Lazy::new(build_type_processor_map);
