name: "Build, check, test, release common"
on:
  workflow_call:
    inputs:
      upload_artifacts:
        required: true
        type: boolean
        default: false
        description: "Upload artifacts to GitHub for consumption by fuzzcorp"


jobs:
  test:
    name: cargo check + test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.76.0
      - uses: Swatinem/rust-cache@v2
        with: 
          cache-all-crates: true # we do this because we have a crapload of crates used for testing/CI

      - name: Install protobuf
        run: sudo apt-get install protobuf-compiler

      - name: Clone protosol
        run: make fetch_proto

      - name: Check lints and clippy
        run: |
          rustup component add rustfmt
          rustup component add clippy
          cargo fmt --all -- --check
          cargo clippy --all -- -D warnings 

      - name: Test
        run: |
          cargo check --release
          cargo test --release

      - name: Run build
        run: make -j shared_obj test_exec_instr

      - name: Run test-vectors
        run: |
          ./scripts/run_test_vectors.sh

      - uses: actions/upload-artifact@v4
        if: ${{ inputs.upload_artifacts }}
        with:
          name: libsolfuzz-agave.so
          path: ./target/x86_64-unknown-linux-gnu/release/libsolfuzz_agave.so
      
      - name: Upload stubbed so
        uses: actions/upload-artifact@v4
        if: ${{ inputs.upload_artifacts }}
        with:
          name: libsolfuzz-agave-stubbed.so
          path: ./target/x86_64-unknown-linux-gnu/release/libsolfuzz_agave_stubbed.so
