name: "Build, check, test, release common"
on:
  workflow_call:

jobs:
  lint:
    name: check lints and clippy
    runs-on: [self-hosted]
    concurrency:
      group: on-pull-request_lint_${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      # TODO: change back to stable once rust releases the coverage fix
      # - uses: dtolnay/rust-toolchain@1.86.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2025-10-30
          override: true
          components: "clippy, rustfmt"

      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true # we do this because we have a crapload of crates used for testing/CI

      - name: Check lints and clippy
        run: |
          cargo fmt --all -- --check
          cargo clippy --all --locked -- -D warnings

  test:
    name: cargo check + test
    runs-on: [self-hosted]
    concurrency:
      group: on-pull-request_test_${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      # TODO: change back to stable once rust releases the coverage fix
      # - uses: dtolnay/rust-toolchain@1.86.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2025-10-30
          override: true

      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true # we do this because we have a crapload of crates used for testing/CI

      - name: Run cargo check + test
        run: |
          cargo check --release --locked
          cargo test --release --locked

  build-shared-objects:
    name: build shared objects
    runs-on: [self-hosted]
    concurrency:
      group: on-pull-request_build-shared-objects_${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      # TODO: change back to stable once rust releases the coverage fix
      # - uses: dtolnay/rust-toolchain@1.86.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2025-10-30
          override: true

      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true # we do this because we have a crapload of crates used for testing/CI

      - name: Build shared objects
        run: make shared_obj_hfuzz

  test-vectors:
    name: run test vectors
    runs-on: [self-hosted]
    concurrency:
      group: on-pull-request_test-vectors_${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      # TODO: change back to stable once rust releases the coverage fix
      # - uses: dtolnay/rust-toolchain@1.86.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2025-10-30
          override: true

      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true # we do this because we have a crapload of crates used for testing/CI

      - name: check out test-vectors (persistent)
        run: |
          COMMIT_SHA=$(cat scripts/test-vectors-commit-sha.txt)
          TEST_VECTORS_PATH="/data/svc_firedancer/test-vectors/${COMMIT_SHA}"
          if [[ ! -d "${TEST_VECTORS_PATH}" ]]; then
            mkdir -p /data/svc_firedancer/test-vectors
            git clone https://github.com/firedancer-io/test-vectors.git "${TEST_VECTORS_PATH}"
            git -C "${TEST_VECTORS_PATH}" checkout "${COMMIT_SHA}"
          fi
          mkdir -p dump
          ln -sf "${TEST_VECTORS_PATH}" dump/test-vectors

      - name: Make binaries
        run: make binaries

      - name: Run test-vectors
        run: |
          ./scripts/run_test_vectors.sh
